version: '3.7'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
    - ./env/app.env
    links:
      - database
    depends_on:
      - database
    ports:
      - 5000:5000
    networks:
      - comp3335-project
    container_name: comp3335-app
  database:
    image: mysql:8.0.31
    env_file:
      - ./env/database.env
    container_name: comp3335-database
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d
      - ./database/config:/etc/mysql/conf.d
      - ./database/log:/var/log/mysql
      - ./database/data:/var/lib/mysql
    command: bash -c "chmod 644 /etc/mysql/conf.d/my.cnf && /entrypoint.sh mysqld"
    ports:
      - 3307:3306
    networks:
      - comp3335-project

networks:
  comp3335-project:
    driver: bridge